name: build
on: [push]
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.version.outputs.package_version }}
    steps:
      - uses: actions/checkout@v3
      - id: version
        run: ./.github/scripts/package_version.sh
  build:
    needs: version
    runs-on: ubuntu-latest
    env:
      package_version: ${{ needs.version.outputs.package_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        with:
          extra-build-deps: devscripts
          before-build-hook: ./.github/scripts/before_build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: firefox-dev-${{ needs.version.outputs.package_version }}
          path: debian/artifacts/*
