name: build

on:
  workflow_dispatch:
  schedule:
  - cron: '55 * * * *'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.version.outputs.package_version }}
    steps:
      - uses: actions/checkout@v3
      - id: version
        run: ./.github/scripts/package_version.sh
  build:
    needs: version
    if: ${{ needs.version.outputs.package_version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      package_version: ${{ needs.version.outputs.package_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        with:
          extra-build-deps: devscripts
          before-build-hook: ./.github/scripts/before_build.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: debian/artifacts/*
          tag: v${{ needs.version.outputs.package_version }}
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        with:
          repository: firefox-dev/debian/bookworm
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
